UsersTable:
    Type: AWS::DynamoDB::Table
    Properties:
        TableName: UsersTable-${self:provider.stage}
        BillingMode: PAY_PER_REQUEST
        AttributeDefinitions:
            - AttributeName: username
              AttributeType: S
            - AttributeName: email
              AttributeType: S
        KeySchema:
            - AttributeName: username
              KeyType: HASH
            - AttributeName: email
              KeyType: RANGE  
        GlobalSecondaryIndexes:
            - IndexName: EmailIndex
              KeySchema:
                - AttributeName: email
                  KeyType: HASH
              Projection:
                ProjectionType: ALL