# Phase 2: Add the EmailIndex GSI after Phase 1 has been deployed
# Replace UsersTable.yml with this content after Phase 1 deployment succeeds
UsersTable:
    Type: AWS::DynamoDB::Table
    Properties:
        TableName: UsersTableV2-${self:provider.stage}
        BillingMode: PAY_PER_REQUEST
        AttributeDefinitions:
            - AttributeName: username
              AttributeType: S
            - AttributeName: email
              AttributeType: S
        KeySchema:
            - AttributeName: username
              KeyType: HASH
        GlobalSecondaryIndexes:
            - IndexName: EmailIndex
              KeySchema:
                - AttributeName: email
                  KeyType: HASH
              Projection:
                ProjectionType: ALL