UsersTable:
    Type: AWS::DynamoDB::Table
    Properties:
        TableName: UsersTableV2-${self:provider.stage}
        BillingMode: PAY_PER_REQUEST
        AttributeDefinitions:
            - AttributeName: username
              AttributeType: S
        KeySchema:
            - AttributeName: username
              KeyType: HASH
        # Phase 1: No GSI - this removes any existing GSI