service: aws-nestjs-dynamodb

plugins:
  - serverless-esbuild
  - serverless-offline
  - serverless-api-gateway-caching
provider:
  name: aws
  tracing:
    apiGateway: true
    lambda: true
  runtime: nodejs16.x
  memorySize: 512
  architecture: x86_64
  stage: ${opt:stage, 'dev'}
  region: us-east-1
  environment:
    USERS_TABLE_NAME: ${self:custom.UsersTable.name}
  iam:
    role:
      statements:
        - ${file(iam/UsersTableIAM.yml):UsersTableIAM}
  apiGateway:
    minimumCompressionSize: 1024
    shouldStartNameWithService: true
    description: aws-nestjs-dynamodb

package:
  individually: true

resources:
  Resources:
    UsersTable: ${file(resources/UsersTable.yml):UsersTable}  

functions:
  main: # The name of the lambda function
    handler: src/lambda.handler # The module 'handler' is exported in the file 'src/lambda'
    events:
      - http:
          method: any
          path: /{any+}
          cors: true
          caching:
            enabled: true
custom:
  UsersTable:
    name: !Ref UsersTable
    arn: !GetAtt UsersTable.Arn
  esbuild:
    bundle: true
    minify: false
    sourcemap: true
    exclude:
      - aws-sdk
    external:
      - class-transformer
      - '@nestjs/microservices'
      - '@nestjs/websockets'
      - '@nestjs/platform-socket.io'
    target: node16
    define:
      require.resolve: undefined
    platform: node
    concurrency: 10
