service:
  name: aws-nestjs-dynamodb

plugins:
  - '@hewmen/serverless-plugin-typescript'
  - serverless-plugin-optimize
  - serverless-offline
  - serverless-api-gateway-caching
provider:
  name: aws
  tracing:
    apiGateway: true
    lambda: true
  runtime: nodejs12.x
  memorySize: 512
  architecture: arm64
  stage: ${opt:stage, 'dev'}
  region: us-east-1
  lambdaHashingVersion: 20201221
  environment:
    USERS_TABLE_NAME: ${self:custom.UsersTable.name}
  iamRoleStatements:
    - ${file(iam/UsersTableIAM.yml):UsersTableIAM}
  apiGateway:
    minimumCompressionSize: 1024
    shouldStartNameWithService: true
    description: aws-nestjs-dynamodb

package:
  individually: true

resources:
  Resources:
    UsersTable: ${file(resources/UsersTable.yml):UsersTable}  

functions:
  main: # The name of the lambda function
    handler: src/lambda.handler # The module 'handler' is exported in the file 'src/lambda'
    events:
      - http:
        method: get
        cors: true
        caching:
          enabled: true
      - http:
          method: any
          path: /{any+}
          cors: true

custom:
  UsersTable:
    name: !Ref UsersTable
    arn: !GetAtt UsersTable.Arn
