service:
  name: aws-nestjs-dynamodb

plugins:
  - '@hewmen/serverless-plugin-typescript'
  - serverless-plugin-optimize
  - serverless-offline
  # - serverless-plugin-warmup

# custom:
#   # Enable warmup on all functions (only for production and staging)
#   warmup:
#       enabled: true

provider:
    name: aws
    tracing:
        apiGateway: true
        lambda: true
    runtime: nodejs12.x
    memorySize: 256
    stage: ${opt:stage, 'dev'}
    region: us-east-1
    lambdaHashingVersion: 20201221
    environment:
        USERS_TABLE_NAME: ${self:custom.UsersTable.name}
    iamRoleStatements:
        - ${file(iam/UsersTableIAM.yml):UsersTableIAM}
    apiGateway:
      shouldStartNameWithService: true
      description: aws-nestjs-dynamodb

package:
  individually: true

functions:
  main: # The name of the lambda function
    handler: src/lambda.handler # The module 'handler' is exported in the file 'src/lambda'
    events:
      - http:
          method: any
          path: /{any+}

custom:
    UsersTable:
        name: !Ref UsersTable
        arn: !GetAtt UsersTable.Arn