name: Deploy to AWS

on:
  push:
    branches: [main]
  workflow_dispatch:

env:
  NODE_VERSION: '20'
  AWS_REGION: 'us-east-1'

jobs:
  test:
    name: Run Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'

      - name: Install frontend dependencies
        run: npm ci

      - name: Install backend dependencies
        run: |
          cd server-src
          npm ci

      - name: Run frontend tests
        run: npm run test:ci

      - name: Run backend tests
        run: |
          cd server-src
          npm test

  deploy-backend:
    name: Deploy Backend (Lambda)
    runs-on: ubuntu-latest
    needs: test
    environment: production
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Install Serverless Framework v3 (stable)
        run: npm install -g serverless@3.38.0

      - name: Install backend dependencies
        run: |
          cd server-src
          npm ci

      - name: Build backend
        run: |
          cd server-src
          npm run build

      - name: Deploy backend with Serverless Framework
        run: |
          cd server-src
          serverless deploy --stage prod --region ${{ env.AWS_REGION }}
        env:
          # Disable analytics and usage tracking to avoid auth issues
          SERVERLESS_DISABLE_USAGE_TRACKING: true
          SLS_DISABLE_ANALYTICS: true
          SLS_DISABLE_TELEMETRY: true
          # Use existing AWS credentials
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

  deploy-frontend:
    name: Deploy Frontend (S3)
    runs-on: ubuntu-latest
    needs: test
    environment: production
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Install dependencies
        run: npm ci

      - name: Build Angular app for production
        run: npm run build:prod

      - name: Deploy to S3
        run: |
          aws s3 sync dist/ s3://${{ secrets.S3_BUCKET_NAME }} --delete
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      - name: Invalidate CloudFront (if configured)
        run: |
          if [ ! -z "${{ secrets.CLOUDFRONT_DISTRIBUTION_ID }}" ]; then
            echo "Attempting CloudFront cache invalidation..."
            if aws cloudfront create-invalidation --distribution-id ${{ secrets.CLOUDFRONT_DISTRIBUTION_ID }} --paths "/*" 2>/dev/null; then
              echo "✅ CloudFront cache invalidation successful"
            else
              echo "⚠️ CloudFront invalidation failed (possibly due to permissions)"
              echo "Frontend deployed to S3 successfully, but cache may need manual invalidation"
              echo "This is not critical - the deployment was successful"
            fi
          else
            echo "CloudFront distribution ID not configured, skipping invalidation"
          fi
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        continue-on-error: true

  notify:
    name: Deployment Notification
    runs-on: ubuntu-latest
    needs: [deploy-backend, deploy-frontend]
    if: always()
    steps:
      - name: Deployment Success
        if: needs.deploy-backend.result == 'success' && needs.deploy-frontend.result == 'success'
        run: |
          echo "✅ Deployment successful!"
          echo "Frontend: Deployed to S3"
          echo "Backend: Deployed to AWS Lambda"
          echo "Application should be live at: ${{ secrets.APP_URL || 'https://brutalpatches.com' }}"

      - name: Deployment Failure
        if: needs.deploy-backend.result != 'success' || needs.deploy-frontend.result != 'success'
        run: |
          echo "❌ Deployment failed!"
          echo "Backend status: ${{ needs.deploy-backend.result }}"
          echo "Frontend status: ${{ needs.deploy-frontend.result }}"
          exit 1